all: lights

lights:
	gcc -Wall -Wextra -pedantic -std=gnu99 -g lights.c ../../lib/c/liblmp.c ../../lib/c/lmp.c ../../lib/c/lt_string.c ../../lib/c/lt_arena.c -o ~/.local/bin/lights

clean:
	rm ~/.local/bin/lights
